version: "3"
services:
# below specify each container/service details
# Starting with name and then configs for each.
  article-analyzer:
    build: .
    restart: always
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.rule=Host(`localhost`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public


networks:
  traefik-public:
    external: true





